apiVersion: v1
kind: Template
labels:
  app: jenkins-agent-klar
  template: jenkins-agent-klar-buildconfig
metadata:
  annotations:
    description: Jenkins Agent Klar Image - BuildConfig
      see https://github.com/faust64/docker-jenkins-agent-klar
    iconClass: icon-openshift
    openshift.io/display-name: Jenkins Agent Klar
    tags: jenkins-agent-klar
  name: jenkins-agent-klar-buildconfig
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Builds Jenkins Agent Klar images
    labels:
      name: jak-${JAK_REPOSITORY_REF}
    name: jak-${JAK_REPOSITORY_REF}
  spec:
    failedBuildsHistoryLimit: 1
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
    source:
      contextDir: /
      git:
        uri: ${JAK_REPOSITORY_URL}
        ref: "${JAK_REPOSITORY_REF}"
      type: Git
    strategy:
      type: Docker
      dockerStrategy:
        env:
        - name: DO_UPGRADE
          value: foo
        forcePull: false
    output:
      to:
        kind: ImageStreamTag
        name: jenkins-agent-klar:${JAK_REPOSITORY_REF}
    triggers:
    - type: ConfigChange
parameters:
- name: JAK_REPOSITORY_REF
  description: Set this to a branch name, tag or other ref of your repository if you are not using the default branch
  displayName: Git Reference
  required: true
  value: master
- name: JAK_REPOSITORY_URL
  description: The URL of the repository with your Jenkins Agent Klar Dockerfile
  displayName: Git Repository URL
  required: true
  value: https://github.com/faust64/docker-jenkins-agent-klar.git
